"""Strict operation schemas, loaded only when record editing is discovered."""

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field


class OperationModel(BaseModel):
    model_config = ConfigDict(extra="forbid", strict=True)


class FieldPath(OperationModel):
    tag: str
    index: int = Field(ge=0)


class AddNote(OperationModel):
    op: Literal["add_note"]
    record_id: str
    text: str
    path: list[FieldPath] = Field(default_factory=list)


class AddSource(OperationModel):
    op: Literal["add_source"]
    title: str
    author: str = ""
    publication: str = ""
    source_id: str | None = None
    repository_id: str | None = None
    note: str = ""


class AddEvent(OperationModel):
    op: Literal["add_event"]
    record_id: str
    tag: str
    source_id: str
    date: str = ""
    place: str = ""
    description: str = ""
    page: str = ""


class AddCitation(OperationModel):
    op: Literal["add_citation"]
    record_id: str
    path: list[FieldPath]
    source_id: str
    page: str = ""
    text: str = ""
    url: str = ""


class FieldNode(OperationModel):
    """A GEDCOM subtree; levels and line continuations are generated by the editor."""

    tag: str
    value: str = ""
    children: list[FieldNode] = Field(default_factory=list)


class AddField(OperationModel):
    op: Literal["add_field"]
    record_id: str
    field: FieldNode
    path: list[FieldPath] = Field(default_factory=list)
    index: int | None = Field(default=None, ge=0)


class UpdateField(OperationModel):
    op: Literal["update_field"]
    record_id: str
    path: list[FieldPath] = Field(default_factory=list)
    expected_sha256: str
    value: str
    tag: str | None = None


class ReplaceField(OperationModel):
    op: Literal["replace_field"]
    record_id: str
    path: list[FieldPath] = Field(min_length=1)
    expected_sha256: str
    field: FieldNode


class RemoveField(OperationModel):
    op: Literal["remove_field"]
    record_id: str
    path: list[FieldPath] = Field(min_length=1)
    expected_sha256: str


class AddRecord(OperationModel):
    op: Literal["add_record"]
    record_id: str
    tag: str
    value: str = ""
    fields: list[FieldNode] = Field(default_factory=list)


class RemoveRecord(OperationModel):
    op: Literal["remove_record"]
    record_id: str
    expected_sha256: str


class UpdateRelationship(OperationModel):
    op: Literal["update_relationship"]
    family_id: str
    individual_id: str
    role: Literal["HUSB", "WIFE", "CHIL"]
    expected_sha256: str
    pedigree: str | None = None
    status: str | None = None


class ReplaceValue(OperationModel):
    op: Literal["replace_value"]
    record_id: str
    path: list[FieldPath]
    old_value: str
    value: str


class AddIndividual(OperationModel):
    op: Literal["add_individual"]
    individual_id: str
    name: str
    sex: Literal["M", "F", "U"] = "U"
    note: str = ""


class UpdateName(OperationModel):
    op: Literal["update_name"]
    individual_id: str
    old_name: str
    name: str
    given_name: str
    surname: str
    name_index: int = Field(default=0, ge=0)


class AddFamily(OperationModel):
    op: Literal["add_family"]
    family_id: str


class AddRelationship(OperationModel):
    op: Literal["add_relationship"]
    family_id: str
    individual_id: str
    role: Literal["HUSB", "WIFE", "CHIL"]
    pedigree: str = ""
    status: str = ""


class RemoveRelationship(OperationModel):
    op: Literal["remove_relationship"]
    family_id: str
    individual_id: str
    role: Literal["HUSB", "WIFE", "CHIL"]
    force: bool = False


class DeleteIndividual(OperationModel):
    op: Literal["delete_individual"]
    individual_id: str
    force: bool = False


class DeleteIndividuals(OperationModel):
    op: Literal["delete_individuals"]
    individual_ids: list[str]
    force: bool = False


class DeleteFamily(OperationModel):
    op: Literal["delete_family"]
    family_id: str
    force: bool = False


class DeleteFamilies(OperationModel):
    op: Literal["delete_families"]
    family_ids: list[str]
    force: bool = False


class MergeIndividuals(OperationModel):
    op: Literal["merge_individuals"]
    source_id: str
    target_id: str
    identity_evidence: str
    force: bool = False


ChangeOperation = Annotated[
    AddNote
    | AddSource
    | AddEvent
    | AddCitation
    | ReplaceValue
    | AddIndividual
    | UpdateName
    | AddFamily
    | AddRelationship
    | RemoveRelationship
    | DeleteIndividual
    | DeleteIndividuals
    | DeleteFamily
    | DeleteFamilies
    | MergeIndividuals
    | AddField
    | UpdateField
    | ReplaceField
    | RemoveField
    | AddRecord
    | RemoveRecord
    | UpdateRelationship,
    Field(discriminator="op"),
]
ChangeBatch = Annotated[list[ChangeOperation], Field(min_length=1, max_length=50)]
